name: perseus
description: Persistence ORM library for DART.
# version: 1.0.0
# homepage:
# author: Xabi Gonzalez <xabiergonzalez@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
  protoc_plugin: ^0.10.5
  


